# Generated by Django 5.0.4 on 2024-04-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='GGua0VplcZU', on_delete=django.db.models.deletion.CASCADE, to='backend.category'),
            preserve_default=False,
        ),
    ]
